name: atol

services:
  atol-server:
    container_name: atol-go-server
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-plain
    environment:
      HTTP_ADDR: ":8080"
      SETTINGS_PATH: "/data/settings.json"
      IMAGE_EDITOR_PATH: "/data/image-editor"
      ATOL_LIBRARY_PATH: "/opt/atol/lib"
      GODEBUG: "asyncpreemptoff=1"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped
